django_project/urls.py
from django.contrib import admin
from django.urls import include, path

import authentification

urlpatterns = [
    path('', include("project_app.urls")),
    path('admin/', admin.site.urls),
]

project_app/urls.py
from django.urls import path
from . import views
import authentification.views as auth

urlpatterns = [
    path('', views.home, name='home'),
    path('connexion/', auth.LoginPageView.as_view(), name="connexion"),
    path('logout/', auth.logout_user, name='logout'),
    path('users/', views.user_home, name='home_user'),
    path('users/add/', views.add_user, name='add_user'),
    path('users/<int:user_id>/', views.user_details, name='user_details'),
    path('users/<int:user_id>/delete/', views.delete_user, name='delete_user'),
    path('projects/add/', views.add_project, name='add_project'),
    path('projects/<int:project_id>/', views.project_details, name='project_details'),
    path('project/edit/<int:project_id>/', views.edit_project, name='edit_project'),
    path('projects/<int:project_id>/delete/', views.delete_project, name='delete_project'),
    path('leaves/add/', views.add_leave, name='add_leave'),
    path('leaves/', views.home_leave, name='home_leave'),
    path('leaves/<int:leave_id>/', views.leave_details, name='leave_details'),
    path('leaves/<int:leave_id>/delete/', views.delete_leave, name='delete_leave'),
    path('project/<int:project_id>/add_task/', views.add_task_to_project, name='add_task_to_project'),
    path('task/<int:task_id>/', views.task_details, name='task_details'),
    path('task/edit/<int:task_id>/', views.edit_task, name='edit_task'),
    path('task/<int:task_id>/delete/', views.delete_task, name='delete_task'),
]

authentification/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    EMPLOYER = 'EMPLOYER'
    MANAGER = 'MANAGER'

    ROLE_CHOICES = (
        (EMPLOYER, 'employer'),
        (MANAGER, 'manager'),
    )
    user_role = models.CharField(max_length=30, choices=ROLE_CHOICES, verbose_name='Rôle')

templates/connexion.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="{% static 'css/connexion.css' %}" rel="stylesheet">
</head>
<body>

    <div class="form-container">
        <h1>Connexion</h1>
        <form method="post">
            {% csrf_token %}
            <label for="username">Nom d'utilisateur :</label>
            <input type="text" id="username" name="username">
            <br>
            <label for="password">Mot de passe :</label>
            <input type="password" id="password" name="password">
            <br>
            <input href="{% url 'connexion' %}" type="submit" value="Se connecter">
        </form>
























</body>
</html>

templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <title>Project Manager</title>
</head>
<body>

<div class="container-fluid">
    <div class="row flex-sm-nowrap">
        {% include 'navigation.html' %}

        <!-- Page content -->
        <div class="col py-3">
            <h2>Projects</h2>
            <div class="my-4">
                {% csrf_token %}
                <!-- Link to the page for adding new projects -->

                <a class="btn btn-dark btn-sm d-inline-flex" type="button" href="{% url 'add_project' %}">
                    <svg class="me-1" xmlns="http://www.w3.org/2000/svg" width="16" fill="currentColor"
                         viewBox="0 0 16 16">
                        <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4"></path>
                    </svg>
                    <span class="me-2">New Project</span>
                </a>

            </div>
            <hr>
            <div class="table-responsive small">
                <table class="table table-borderless table-hover">
                    <thead>
                    <tr>
                        <th>Project name</th>
                        <th>Owner</th>
                        <th>Status</th>
                        <th>Due Date</th>
                        <th>Progress</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for project in projects %}
                        <tr>
                            <td>{{ project.project_name }}</td>
                            <td>{{ project.project_manager }}</td>
                            <td>
                                {% if project.status == 'pending' %}
                                    <span class="badge text-bg-secondary">En attente</span>
                                {% elif project.status == 'delivered' %}
                                    <span class="badge text-bg-success">Livré</span>
                                {% elif project.status == 'planned' %}
                                    <span class="badge text-bg-light">Planifié</span>
                                {% elif project.status == 'paused' %}
                                    <span class="badge text-bg-danger">En pause</span>
                                {% endif %}
                            </td>
                            <td>
                                <small class="text-secondary">{{ project.delivery_date }}</small>
                            </td>
                            <td>
                                <div class="row align-items-center">
                                    <div class="col">
                                        <div class="progress" role="progressbar"
                                             aria-valuenow="{{ project.progress_percentage }}" aria-valuemin="0"
                                             aria-valuemax="100">
                                            <div class="progress-bar bg-success"
                                                 style="width: {{ project.progress_percentage }}%"></div>
                                        </div>
                                    </div>
                                    <small class="col-3">{{ project.progress_percentage }}%</small>
                                </div>
                            </td>
                            <td class="text-end">
                                <a href="{% url 'project_details' project.id %}" class="link-dark opacity-75">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                         fill="currentColor" class="bi bi-info-circle" viewBox="0 0 16 16">
                                        <title>{{ project.project_name }} details</title>
                                        <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0"></path>
                                        <path d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8m8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7"></path>
                                    </svg>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>

            </div>
    </div>
</div>
</div>
</body>
</html>

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <title>Project Manager</title>
</head>
<body>
<div class="container-fluid">
    <div class="row flex-sm-nowrap">
        <!--  Navigation -->
        <div class="d-flex flex-column flex-shrink-0 p-3 text-bg-dark min-vh-100" style="width: 280px;">
            <a href="/" class="navbar-brand d-flex gap-3 mb-4 mt-2">
                <svg xmlns="http://www.w3.org/2000/svg" width="1.5rem" fill="currentColor"
                     class="bi bi-clipboard-data-fill"
                     viewBox="0 0 16 16">
                    <path d="M6.5 0A1.5 1.5 0 0 0 5 1.5v1A1.5 1.5 0 0 0 6.5 4h3A1.5 1.5 0 0 0 11 2.5v-1A1.5 1.5 0 0 0 9.5 0zm3 1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 .5-.5z"></path>
                    <path d="M4 1.5H3a2 2 0 0 0-2 2V14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V3.5a2 2 0 0 0-2-2h-1v1A2.5 2.5 0 0 1 9.5 5h-3A2.5 2.5 0 0 1 4 2.5zM10 8a1 1 0 1 1 2 0v5a1 1 0 1 1-2 0zm-6 4a1 1 0 1 1 2 0v1a1 1 0 1 1-2 0zm4-3a1 1 0 0 1 1 1v3a1 1 0 1 1-2 0v-3a1 1 0 0 1 1-1"></path>
                </svg>
                <span class="fs-4">Project Manager</span>
            </a>
            <ul class="nav nav-pills flex-column mb-auto">
                <li class="nav-item">
                    <a href="/" class="nav-link text-white current">
                        <svg class="bi pe-none me-2" width="16" height="16" xmlns="http://www.w3.org/2000/svg"
                             fill="currentColor" viewBox="0 0 16 16">
                            <path d="M4 11a1 1 0 1 1 2 0v1a1 1 0 1 1-2 0zm6-4a1 1 0 1 1 2 0v5a1 1 0 1 1-2 0zM7 9a1 1 0 0 1 2 0v3a1 1 0 1 1-2 0z"></path>
                            <path d="M4 1.5H3a2 2 0 0 0-2 2V14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V3.5a2 2 0 0 0-2-2h-1v1h1a1 1 0 0 1 1 1V14a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V3.5a1 1 0 0 1 1-1h1z"></path>
                            <path d="M9.5 1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 .5-.5zm-3-1A1.5 1.5 0 0 0 5 1.5v1A1.5 1.5 0 0 0 6.5 4h3A1.5 1.5 0 0 0 11 2.5v-1A1.5 1.5 0 0 0 9.5 0z"></path>
                        </svg>
                        Projects
                    </a>
                </li>
                <li>
                    <a href="#" class="nav-link text-white">
                        <svg class="bi pe-none me-2" width="16" height="16" xmlns="http://www.w3.org/2000/svg"
                             fill="currentColor" viewBox="0 0 16 16">
                            <path d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1zm4-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6m-5.784 6A2.24 2.24 0 0 1 5 13c0-1.355.68-2.75 1.936-3.72A6.3 6.3 0 0 0 5 9c-4 0-5 3-5 4s1 1 1 1zM4.5 8a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5"></path>
                        </svg>
                        Users
                    </a>
                </li>
            </ul>
            <hr>
            <div class="dropdown">
                <a href="#" class="d-flex align-items-center gap-2 text-white text-decoration-none dropdown-toggle"
                   data-bs-toggle="dropdown" aria-expanded="false">
                    <svg xmlns="http://www.w3.org/2000/svg" width="1.25rem" fill="currentColor" viewBox="0 0 16 16">
                        <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0"></path>
                        <path fill-rule="evenodd"
                              d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1"></path>
                    </svg>
                    <strong>user</strong>
                </a>
                <ul class="dropdown-menu dropdown-menu-dark text-small shadow">
                    <li><a class="dropdown-item" href="#">Settings</a></li>
                    <li><a class="dropdown-item" href="#">Profile</a></li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item" href="#">Sign out</a></li>
                </ul>
            </div>
        </div>

        <!-- Page content -->
        <div class="col py-3">
            <h2>Projects</h2>
            <div class="my-4">
                <!-- Link to the page for adding new projects -->
                <a class="btn btn-dark btn-sm d-inline-flex" type="button" href="{% url 'add_project' %}">
                    <svg class="me-1" xmlns="http://www.w3.org/2000/svg" width="16" fill="currentColor"
                         viewBox="0 0 16 16">
                        <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4"></path>
                    </svg>
                    <span class="me-2">New Project</span>
                </a>
            </div>
            <hr>
            <div class="table-responsive small">
                <table class="table table-borderless table-hover">
                    <thead>
                    <tr>
                        <th>Project name</th>
                        <th>Owner</th>
                        <th>Status</th>
                        <th>Due Date</th>
                        <th>Progress</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for project in projects %}
                        <tr>
                            <td>{{ project.project_name }}</td>
                            <td>{{ project.project_manager }}</td>
                            <td>
                                {% if project.status == 'pending' %}
                                    <span class="badge text-bg-secondary">En attente</span>
                                {% elif project.status == 'delivered' %}
                                    <span class="badge text-bg-success">Livré</span>
                                {% elif project.status == 'planned' %}
                                    <span class="badge text-bg-light">Planifié</span>
                                {% elif project.status == 'paused' %}
                                    <span class="badge text-bg-danger">En pause</span>
                                {% endif %}
                            </td>
                            <td>
                                <small class="text-secondary">{{ project.delivery_date }}</small>
                            </td>
                            <td>
                                <div class="row align-items-center">
                                    <div class="col">
                                        <div class="progress" role="progressbar"
                                             aria-valuenow="{{ project.progress_percentage }}" aria-valuemin="0"
                                             aria-valuemax="100">
                                            <div class="progress-bar bg-success"
                                                 style="width: {{ project.progress_percentage }}%"></div>
                                        </div>
                                    </div>
                                    <small class="col-3">{{ project.progress_percentage }}%</small>
                                </div>
                            </td>
                            <td class="text-end">
                                <a href="{% url 'project_details' project.id %}" class="link-dark opacity-75">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                         fill="currentColor" class="bi bi-info-circle" viewBox="0 0 16 16">
                                        <title>{{ project.project_name }} details</title>
                                        <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0"></path>
                                        <path d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8m8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7"></path>
                                    </svg>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        
        {% include 'Leaves/leave_list.html' %}

    </div>
</div>
</body>
</html>

templates/navigation.html
<!-- Navigation -->
<div class="d-flex flex-column flex-shrink-0 p-3 text-bg-dark min-vh-100" style="width: 280px;">
    <a href="{% url 'home' %}" class="navbar-brand d-flex gap-3 mb-4 mt-2">
        <svg xmlns="http://www.w3.org/2000/svg" width="1.5rem" fill="currentColor"
             class="bi bi-clipboard-data-fill"
             viewBox="0 0 16 16">
            <path d="M6.5 0A1.5 1.5 0 0 0 5 1.5v1A1.5 1.5 0 0 0 6.5 4h3A1.5 1.5 0 0 0 11 2.5v-1A1.5 1.5 0 0 0 9.5 0zm3 1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 .5-.5z"></path>
            <path d="M4 1.5H3a2 2 0 0 0-2 2V14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V3.5a2 2 0 0 0-2-2h-1v1A2.5 2.5 0 0 1 9.5 5h-3A2.5 2.5 0 0 1 4 2.5zM10 8a1 1 0 1 1 2 0v5a1 1 0 1 1-2 0zm-6 4a1 1 0 1 1 2 0v1a1 1 0 1 1-2 0zm4-3a1 1 0 0 1 1 1v3a1 1 0 1 1-2 0v-3a1 1 0 0 1 1-1"></path>
        </svg>
        <span class="fs-4">Project Manager</span>
    </a>
    <ul class="nav nav-pills flex-column mb-auto">
    <li class="nav-item">
        <a href="{% url 'home' %}" class="nav-link text-white {% if request.path|slice:":9" == '/projects' or request.path|slice:":6" == '/task/' or request.path == '/' %}current{% endif %}">
            <svg class="bi pe-none me-2" width="16" height="16" xmlns="http://www.w3.org/2000/svg"
                 fill="currentColor" viewBox="0 0 16 16">
                <path d="M4 11a1 1 0 1 1 2 0v1a1 1 0 1 1-2 0zm6-4a1 1 0 1 1 2 0v5a1 1 0 1 1-2 0zM7 9a1 1 0 0 1 2 0v3a1 1 0 1 1-2 0z"></path>
                <path d="M4 1.5H3a2 2 0 0 0-2 2V14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V3.5a2 2 0 0 0-2-2h-1v1h1a1 1 0 0 1 1 1V14a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V3.5a1 1 0 0 1 1-1h1z"></path>
                <path d="M9.5 1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 .5-.5zm-3-1A1.5 1.5 0 0 0 5 1.5v1A1.5 1.5 0 0 0 6.5 4h3A1.5 1.5 0 0 0 11 2.5v-1A1.5 1.5 0 0 0 9.5 0z"></path>
            </svg>
            Projects
        </a>
    </li>
        {% if perms.authentification.view_user %}
    <li>
        <a href="{% url 'home_user' %}" class="nav-link text-white {% if request.path|slice:":6" == '/users' %}current{% endif %}">
            <svg class="bi pe-none me-2" width="16" height="16" xmlns="http://www.w3.org/2000/svg"
                 fill="currentColor" viewBox="0 0 16 16">
                <path d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1zm4-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6m-5.784 6A2.24 2.24 0 0 1 5 13c0-1.355.68-2.75 1.936-3.72A6.3 6.3 0 0 0 5 9c-4 0-5 3-5 4s1 1 1 1zM4.5 8a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5"></path>
            </svg>
            Users
        </a>
    </li>
{% endif %}
        {% if perms.project_app.add_leave %}
        <li>
        <a href="{% url 'home_leave' %}" class="nav-link text-white {% if request.path|slice:":7" == '/leaves' %}current{% endif %}">
            <svg class="bi pe-none me-2" width="16" height="16" xmlns="http://www.w3.org/2000/svg"
                 fill="currentColor" viewBox="0 0 16 16">
                <path d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1zm4-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6m-5.784 6A2.24 2.24 0 0 1 5 13c0-1.355.68-2.75 1.936-3.72A6.3 6.3 0 0 0 5 9c-4 0-5 3-5 4s1 1 1 1zM4.5 8a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5"></path>
            </svg>
            Leaves
        </a>
    </li>
        {% endif %}
</ul>

    <hr>
    <div class="dropdown">
        <a href="#" class="d-flex align-items-center gap-2 text-white text-decoration-none dropdown-toggle"
           data-bs-toggle="dropdown" aria-expanded="false">
            <svg xmlns="http://www.w3.org/2000/svg" width="1.25rem" fill="currentColor" viewBox="0 0 16 16">
                <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0"></path>
                <path fill-rule="evenodd"
                      d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1"></path>
            </svg>
            <strong>{% block logged_in_username %}{{ logged_in_username }}{% endblock %}</strong>
        </a>
        <ul class="dropdown-menu dropdown-menu-dark text-small shadow">
            <li><a class="dropdown-item" href="#">Settings</a></li>
            <li><a class="dropdown-item" href="#">Profile</a></li>
            <li>
                <hr class="dropdown-divider">
            </li>
            <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
        </ul>
    </div>
</div>